// "use client"
// export const metadata = {
//     title: "Blog articulo",
//     description: "Blog articulo",
// }
import Title from '@/components/pagescomponents/Title'
import React from 'react'
import { POST } from '../page';
import Link from 'next/link';
// import { useRouter } from 'next/navigation';

export function generateMetadata({params}){
    const post = POST.find(x=>x.slug === params.id);
    return {
        title: post.title,
        description: post.title+ " Blog - Generated by create next app"
    }
}

function Id({params}) {
    const post = POST.find(x=>x.slug === params.id);
    // const router= useRouter();
    // const handleClickBack=()=>{
    //     // router.back();
    //     router.push('/blog');
    // }
    return (
        <>
            <Title title={post.title}/>
            <p className='text-center mb-5'>{post.content}</p>
            <div className='text-center'>
                {/* <button className='bg-indigo-500 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded'
                onClick={handleClickBack}>Back</button> */}
                <Link
                className='bg-indigo-500 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded'
                href="/blog">Back</Link>
            </div>
        </>
    )
}

export default Id
