import '../globals.css'
import { Inter } from 'next/font/google'
 
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function MarketingLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <p>Marketing Layout</p>
        {children}</body>
    </html>
  )
}
